import { SETTINGS_ITEMS, type SettingsItem } from "./settingsItems";
import type { MainContentView } from "../mainContent/types";

export type SettingsSearchEntryKind = "page" | "tab" | "section" | "field";

export type SettingsSearchTrailItem = {
  labelKey: string | null;
  label: string;
};

export type SettingsSearchEntry = {
  id: string;
  view: MainContentView;
  kind: SettingsSearchEntryKind;
  labelKey: string | null;
  label: string;
  trail: SettingsSearchTrailItem[];
  keywords: string[];
};

type RawEntry = [
  id: string,
  kind: SettingsSearchEntryKind,
  labelKey: string | null,
  label: string,
  trail: string[],
  keywords: string[],
];

type RawGroup = {
  view: MainContentView;
  entries: RawEntry[];
};

/** 与所属设置页同名、仅用于拼接 tabTrail 的 tab 条目（不单独出现在搜索结果里）。 */
const HIDDEN_ENTRY_IDS: ReadonlySet<string> = new Set([
  "general.tab.general",
  "browser.tab.settings",
]);

const RAW_GROUPS: RawGroup[] = [
  {
    view: "general-settings",
    entries: [
      [
        "general.tab.general",
        "tab",
        "settings.generalSettings",
        "General settings",
        [],
        ["general", "通用"],
      ],
      [
        "general.tab.storage",
        "tab",
        "settings.storageTab",
        "Storage & resources",
        [],
        ["storage", "存储", "资源"],
      ],
      [
        "general.tab.privacy",
        "tab",
        "settings.privacyTab",
        "Privacy",
        [],
        ["privacy", "隐私"],
      ],
      [
        "general.tab.about",
        "tab",
        "settings.about",
        "About",
        [],
        ["about", "关于", "版本"],
      ],
      [
        "general.language",
        "section",
        "settings.languageSettings",
        "Language",
        ["general.tab.general"],
        ["language", "语言"],
      ],
      [
        "general.closeBehavior",
        "section",
        "settings.closeBehavior",
        "关闭 Snow APP 时",
        ["general.tab.general"],
        ["close", "关闭", "托盘"],
      ],
      [
        "general.closeBehaviorAction",
        "field",
        "settings.closeBehaviorAction",
        "关闭行为",
        ["general.tab.general"],
        ["最小化", "退出", "每次询问"],
      ],
      [
        "general.teamCollaboration",
        "section",
        "settings.teamCollaboration",
        "团队协作",
        ["general.tab.general"],
        ["team", "团队协作"],
      ],
      [
        "general.teamCollaborationEnabled",
        "field",
        "settings.teamCollaborationEnabled",
        "启用团队协作",
        ["general.tab.general"],
        ["team", "团队", "开关"],
      ],
      [
        "general.attachContext",
        "section",
        "settings.attachContextTitle",
        "会话上下文注入",
        ["general.tab.general"],
        ["context", "上下文", "拖拽会话"],
      ],
      [
        "general.attachContextSingleBudget",
        "field",
        "settings.attachContextSingleBudget",
        "单附件预算（字符）",
        ["general.tab.general"],
        ["attachment", "预算", "附件"],
      ],
      [
        "general.attachContextTotalBudget",
        "field",
        "settings.attachContextTotalBudget",
        "全部附件合计预算（字符）",
        ["general.tab.general"],
        ["attachment", "预算", "合计"],
      ],
      [
        "general.storage.resourceUsage",
        "section",
        "settings.resourceUsage",
        "Resource usage",
        ["general.tab.storage"],
        ["memory", "资源占用"],
      ],
      [
        "general.storage.memory",
        "field",
        "settings.resourceMemory",
        "Memory usage",
        ["general.tab.storage"],
        ["memory", "内存"],
      ],
      [
        "general.storage.optimize",
        "field",
        "settings.resourceOptimize",
        "Optimize disk usage",
        ["general.tab.storage"],
        ["vacuum", "磁盘优化", "回收空间"],
      ],
      [
        "general.storage.clearCache",
        "field",
        "settings.resourceClearCache",
        "Clear app cache",
        ["general.tab.storage"],
        ["cache", "缓存"],
      ],
      [
        "general.storage.cleanup",
        "section",
        "settings.cleanupTitle",
        "Data cleanup",
        ["general.tab.storage"],
        ["cleanup", "数据清理"],
      ],
      [
        "general.storage.cleanupAgeFilter",
        "field",
        "settings.cleanupAgeFilter",
        "Time range",
        ["general.tab.storage"],
        ["time range", "时间范围"],
      ],
      [
        "general.storage.locations",
        "section",
        "settings.storageLocations",
        "Storage locations",
        ["general.tab.storage"],
        ["storage", "存储位置"],
      ],
      [
        "general.storage.runtimeDatabase",
        "field",
        "settings.storageRuntimeDatabase",
        "Runtime database",
        ["general.tab.storage"],
        ["database", "运行数据库"],
      ],
      [
        "general.storage.archiveDatabase",
        "field",
        "settings.storageArchiveDatabase",
        "Archive database",
        ["general.tab.storage"],
        ["database", "归档数据库"],
      ],
      [
        "general.storage.checkpoints",
        "field",
        "settings.storageCheckpoint",
        "Checkpoints",
        ["general.tab.storage"],
        ["checkpoint", "检查点"],
      ],
      [
        "general.storage.uploadedImages",
        "field",
        "settings.storageUpload",
        "Uploaded images",
        ["general.tab.storage"],
        ["upload", "上传图片"],
      ],
      [
        "general.storage.imageLibrary",
        "field",
        "settings.storageImageLibrary",
        "Image library",
        ["general.tab.storage"],
        ["image library", "图库"],
      ],
      [
        "general.appLock",
        "section",
        "settings.appLockTitle",
        "App lock",
        ["general.tab.privacy"],
        ["app lock", "应用锁", "锁屏"],
      ],
      [
        "general.appLock.delay",
        "field",
        "settings.appLockDelay",
        "Lock timing",
        ["general.tab.privacy"],
        ["lock timing", "锁定时长", "失焦"],
      ],
      [
        "general.appLock.totp",
        "section",
        "settings.appLockTotpTitle",
        "Google Authenticator",
        ["general.tab.privacy"],
        ["totp", "验证器", "动态口令"],
      ],
      [
        "general.appLock.unbindVerify",
        "field",
        "settings.appLockUnbindVerify",
        "Unbind verification (6-digit code)",
        ["general.tab.privacy"],
        ["unbind", "解绑验证"],
      ],
      [
        "general.appLock.managePin",
        "section",
        "settings.appLockManagePin",
        "Change or disable the PIN",
        ["general.tab.privacy"],
        ["pin", "修改密码", "关闭应用锁"],
      ],
      [
        "general.appLock.currentPin",
        "field",
        "settings.appLockCurrentPin",
        "Current PIN or 6-digit code",
        ["general.tab.privacy"],
        ["current pin", "当前密码"],
      ],
      [
        "general.appLock.newPin",
        "field",
        "settings.appLockNewPin",
        "New PIN",
        ["general.tab.privacy"],
        ["new pin", "新密码"],
      ],
      [
        "general.appLock.newPinConfirm",
        "field",
        "settings.appLockNewPinConfirm",
        "Confirm new PIN",
        ["general.tab.privacy"],
        ["confirm pin", "确认密码"],
      ],
      [
        "general.appLock.disablePin",
        "field",
        "settings.appLockDisablePin",
        "PIN or 6-digit code to disable the lock",
        ["general.tab.privacy"],
        ["disable lock", "关闭应用锁"],
      ],
      [
        "general.appLock.enable",
        "section",
        "settings.appLockEnableTitle",
        "Set a PIN and enable",
        ["general.tab.privacy"],
        ["enable app lock", "启用应用锁"],
      ],
      [
        "general.about.version",
        "field",
        "settings.version",
        "Version",
        ["general.tab.about"],
        ["version", "版本号"],
      ],
      [
        "general.about.license",
        "section",
        "settings.aboutLicense",
        "开源协议",
        ["general.tab.about"],
        ["license", "许可"],
      ],
      [
        "general.about.privacy",
        "section",
        "settings.aboutPrivacy",
        "隐私说明",
        ["general.tab.about"],
        ["privacy statement", "数据处理"],
      ],
      [
        "general.about.disclaimer",
        "section",
        "settings.aboutDisclaimer",
        "免责声明",
        ["general.tab.about"],
        ["disclaimer", "风险"],
      ],
    ],
  },
  {
    view: "api-settings",
    entries: [
      [
        "api.tab.llm",
        "tab",
        "settings.apiTabLlmModels",
        "LLM models",
        [],
        ["llm", "模型", "接口配置"],
      ],
      [
        "api.tab.imagegen",
        "tab",
        "settings.apiTabImageModels",
        "Image models",
        [],
        ["image", "图像", "生图"],
      ],
      [
        "api.tab.decision",
        "tab",
        "settings.apiTabDecisionModels",
        "Decision models",
        [],
        ["decision", "决策模型", "判定模型"],
      ],
      [
        "api.tab.retry",
        "tab",
        "settings.apiTabRetry",
        "Retry policy",
        [],
        ["retry", "重试"],
      ],
      [
        "api.section.basic",
        "section",
        "settings.formBasic",
        "Basic",
        ["api.tab.llm"],
        ["basic", "基础"],
      ],
      [
        "api.section.promptHeaders",
        "section",
        "settings.formPromptHeaders",
        "Prompt & Headers",
        ["api.tab.llm"],
        ["prompt", "headers", "提示词"],
      ],
      [
        "api.section.models",
        "section",
        "settings.formModels",
        "Models",
        ["api.tab.llm"],
        ["model", "模型"],
      ],
      [
        "api.section.vision",
        "section",
        "settings.formVision",
        "Vision",
        ["api.tab.llm"],
        ["vision", "视觉", "多模态"],
      ],
      [
        "api.section.runtime",
        "section",
        "settings.formRuntime",
        "Runtime",
        ["api.tab.llm"],
        ["runtime", "运行时"],
      ],
      [
        "api.field.profileName",
        "field",
        "settings.apiProfileName",
        "Profile name",
        ["api.tab.llm"],
        ["profile", "配置名", "档案名"],
      ],
      [
        "api.field.baseUrl",
        "field",
        "settings.apiBaseUrl",
        "Base URL",
        ["api.tab.llm"],
        ["url", "接口地址"],
      ],
      [
        "api.field.apiKey",
        "field",
        "settings.apiKey",
        "API key",
        ["api.tab.llm"],
        ["key", "密钥", "token"],
      ],
      [
        "api.field.requestMethod",
        "field",
        "settings.apiRequestMethod",
        "Request method",
        ["api.tab.llm"],
        ["method", "请求方式"],
      ],
      [
        "api.field.systemPrompts",
        "field",
        "settings.apiSystemPrompts",
        "System prompts",
        ["api.tab.llm"],
        ["system prompt", "系统提示词"],
      ],
      [
        "api.field.advancedModel",
        "field",
        "settings.apiAdvancedModel",
        "Advanced model",
        ["api.tab.llm"],
        ["advanced model", "高级模型"],
      ],
      [
        "api.field.maxContext",
        "field",
        "settings.apiMaxContext",
        "Max context (tokens)",
        ["api.tab.llm"],
        ["context", "上下文", "token"],
      ],
      [
        "api.field.maxRetries",
        "field",
        "settings.apiMaxRetries",
        "Max retries",
        ["api.tab.llm"],
        ["retry", "重试次数"],
      ],
      [
        "api.field.systemPromptIds",
        "field",
        "settings.apiCustomHeaderScheme",
        "Custom header scheme",
        ["api.tab.llm"],
        ["headers", "请求头方案"],
      ],
      [
        "api.imagegen.maxConcurrent",
        "field",
        "settings.imagegenMaxConcurrent",
        "Max concurrent generations",
        ["api.tab.imagegen"],
        ["concurrency", "并发", "生图并发"],
      ],
      [
        "api.imagegen.timeout",
        "field",
        "settings.imagegenTimeout",
        "Generation timeout (s)",
        ["api.tab.imagegen"],
        ["timeout", "超时"],
      ],
      [
        "api.imagegen.model",
        "field",
        "settings.imagegenModel",
        "Model",
        ["api.tab.imagegen"],
        ["model", "生图模型"],
      ],
      [
        "api.imagegen.defaultSize",
        "field",
        "settings.imagegenDefaultSize",
        "Default size",
        ["api.tab.imagegen"],
        ["size", "尺寸", "分辨率"],
      ],
      [
        "api.imagegen.streaming",
        "field",
        "settings.imagegenStreaming",
        "Streaming preview",
        ["api.tab.imagegen"],
        ["streaming", "流式预览"],
      ],
      [
        "api.retry.categories",
        "section",
        "settings.retryCategoriesTitle",
        "Retryable error categories",
        ["api.tab.retry"],
        ["category", "可重试错误", "429"],
      ],
      [
        "api.retry.always",
        "field",
        "settings.retryAlways",
        "Retry any error",
        ["api.tab.retry"],
        ["retry all", "总是重试"],
      ],
      [
        "api.retry.customKeywords",
        "field",
        "settings.retryCustomKeywords",
        "Extra keywords",
        ["api.tab.retry"],
        ["keywords", "关键字", "重试关键词"],
      ],
    ],
  },
  {
    view: "image-library",
    entries: [
      [
        "library.search",
        "field",
        "settings.imageLibrarySearchPlaceholder",
        "Search filename, prompt, model…",
        [],
        ["search", "搜索", "提示词"],
      ],
      [
        "library.filter.landscape",
        "field",
        "settings.imageLibraryFilterLandscape",
        "Landscape",
        [],
        ["ratio", "横图", "比例筛选"],
      ],
      [
        "library.filter.square",
        "field",
        "settings.imageLibraryFilterSquare",
        "Square",
        [],
        ["ratio", "方图", "比例筛选"],
      ],
      [
        "library.filter.portrait",
        "field",
        "settings.imageLibraryFilterPortrait",
        "Portrait",
        [],
        ["ratio", "竖图", "比例筛选"],
      ],
      [
        "library.time.today",
        "field",
        "settings.imageLibraryTimeToday",
        "Today",
        [],
        ["time filter", "今天"],
      ],
      [
        "library.time.7d",
        "field",
        "settings.imageLibraryTime7d",
        "Last 7 days",
        [],
        ["time filter", "最近7天"],
      ],
      [
        "library.time.30d",
        "field",
        "settings.imageLibraryTime30d",
        "Last 30 days",
        [],
        ["time filter", "最近30天"],
      ],
      [
        "library.sort.newest",
        "field",
        "settings.imageLibrarySortNewest",
        "Newest first",
        [],
        ["sort", "排序", "最新优先"],
      ],
      [
        "library.sort.oldest",
        "field",
        "settings.imageLibrarySortOldest",
        "Oldest first",
        [],
        ["sort", "排序", "最早优先"],
      ],
      [
        "library.sort.name",
        "field",
        "settings.imageLibrarySortName",
        "By name",
        [],
        ["sort", "排序", "按名称"],
      ],
      [
        "library.album.all",
        "field",
        "settings.imageLibraryAlbumAll",
        "All",
        [],
        ["album", "相册", "全部图片"],
      ],
      [
        "library.album.none",
        "field",
        "settings.imageLibraryAlbumNone",
        "Uncategorized",
        [],
        ["album", "未分类"],
      ],
    ],
  },
  {
    view: "proxy-browser-settings",
    entries: [
      [
        "proxyBrowser.manual",
        "section",
        "settings.proxyBrowserManualTitle",
        "Manual configuration",
        [],
        ["manual", "手动配置"],
      ],
      [
        "proxyBrowser.proxy",
        "section",
        "settings.formProxy",
        "Proxy",
        [],
        ["proxy", "代理"],
      ],
      [
        "proxyBrowser.host",
        "field",
        "settings.proxyHost",
        "Proxy host",
        [],
        ["host", "代理地址"],
      ],
      [
        "proxyBrowser.port",
        "field",
        "settings.proxyPort",
        "Proxy port",
        [],
        ["port", "代理端口"],
      ],
      [
        "proxyBrowser.searchEngine",
        "field",
        "settings.searchEngine",
        "Search engine",
        [],
        ["search engine", "搜索引擎"],
      ],
      [
        "proxyBrowser.browser",
        "section",
        "settings.formBrowser",
        "Browser",
        [],
        ["browser", "浏览器"],
      ],
      [
        "proxyBrowser.browserPath",
        "field",
        "settings.browserPath",
        "Browser executable path",
        [],
        ["browser path", "浏览器路径"],
      ],
      [
        "proxyBrowser.browserDebugPort",
        "field",
        "settings.browserDebugPort",
        "Browser debug port",
        [],
        ["debug port", "调试端口"],
      ],
      [
        "proxyBrowser.blockedSites",
        "section",
        "settings.formBlockedSites",
        "Blocked sites",
        [],
        ["blocked sites", "屏蔽站点", "黑名单"],
      ],
      [
        "proxyBrowser.blockedPatterns",
        "field",
        "settings.blockedPatterns",
        "Regex blocking rules",
        [],
        ["regex", "正则", "屏蔽规则"],
      ],
    ],
  },
  {
    view: "codebase-settings",
    entries: [
      [
        "codebase.section.manual",
        "section",
        "settings.codebaseManualTitle",
        "Manual configuration",
        [],
        ["manual", "手动配置"],
      ],
      [
        "codebase.section.embedding",
        "section",
        "settings.codebaseEmbeddingSettings",
        "Embedding settings",
        [],
        ["embedding", "向量化", "索引"],
      ],
      [
        "codebase.section.reranking",
        "section",
        "settings.codebaseRerankingSettings",
        "Reranking settings",
        [],
        ["rerank", "重排序"],
      ],
      [
        "codebase.section.agentReview",
        "section",
        "settings.codebaseAgentReviewSettings",
        "Agent review settings",
        [],
        ["agent review", "检索审查"],
      ],
      [
        "codebase.section.batchChunking",
        "section",
        "settings.codebaseBatchChunkingSettings",
        "Batch and chunking",
        [],
        ["batch", "chunk", "分块"],
      ],
      [
        "codebase.embedding.type",
        "field",
        "settings.codebaseEmbeddingType",
        "Embedding type",
        [],
        ["type", "向量化服务"],
      ],
      [
        "codebase.embedding.modelName",
        "field",
        "settings.codebaseEmbeddingModelName",
        "Embedding model name",
        [],
        ["embedding", "向量模型"],
      ],
      [
        "codebase.embedding.baseUrl",
        "field",
        "settings.codebaseEmbeddingBaseUrl",
        "Embedding base URL",
        [],
        ["url", "向量化地址"],
      ],
      [
        "codebase.embedding.dimensions",
        "field",
        "settings.codebaseEmbeddingDimensions",
        "Embedding dimensions",
        [],
        ["dimensions", "向量维度"],
      ],
      [
        "codebase.embedding.apiKey",
        "field",
        "settings.codebaseEmbeddingApiKey",
        "Embedding API key",
        [],
        ["key", "向量化密钥"],
      ],
      [
        "codebase.embedding.contextLength",
        "field",
        "settings.codebaseModelContextLength",
        "Model context length (tokens)",
        [],
        ["context", "上下文长度"],
      ],
      [
        "codebase.rerank.modelName",
        "field",
        "settings.codebaseRerankingModelName",
        "Reranking model name",
        [],
        ["rerank", "重排模型"],
      ],
      [
        "codebase.rerank.baseUrl",
        "field",
        "settings.codebaseRerankingBaseUrl",
        "Reranking base URL",
        [],
        ["url", "重排地址"],
      ],
      [
        "codebase.rerank.apiKey",
        "field",
        "settings.codebaseRerankingApiKey",
        "Reranking API key",
        [],
        ["key", "重排密钥"],
      ],
      [
        "codebase.rerank.contextLength",
        "field",
        "settings.codebaseRerankingContextLength",
        "Reranking context length",
        [],
        ["context", "重排上下文"],
      ],
      [
        "codebase.rerank.topN",
        "field",
        "settings.codebaseRerankingTopN",
        "Reranking top N",
        [],
        ["top n", "重排数量"],
      ],
      [
        "codebase.review.model",
        "field",
        "settings.codebaseReviewModel",
        "Review model",
        [],
        ["review model", "审查模型"],
      ],
      [
        "codebase.batch.maxLines",
        "field",
        "settings.codebaseBatchMaxLines",
        "Batch max lines",
        [],
        ["batch", "批量行数"],
      ],
      [
        "codebase.batch.concurrency",
        "field",
        "settings.codebaseBatchConcurrency",
        "Batch concurrency",
        [],
        ["concurrency", "批量并发"],
      ],
      [
        "codebase.chunk.maxLines",
        "field",
        "settings.codebaseChunkingMaxLinesPerChunk",
        "Max lines per chunk",
        [],
        ["chunk", "分块行数"],
      ],
      [
        "codebase.chunk.minLines",
        "field",
        "settings.codebaseChunkingMinLinesPerChunk",
        "Min lines per chunk",
        [],
        ["chunk", "分块行数"],
      ],
      [
        "codebase.chunk.minChars",
        "field",
        "settings.codebaseChunkingMinCharsPerChunk",
        "Min chars per chunk",
        [],
        ["chunk", "最小字符数"],
      ],
      [
        "codebase.chunk.overlap",
        "field",
        "settings.codebaseChunkingOverlapLines",
        "Overlap lines",
        [],
        ["chunk", "重叠行数"],
      ],
    ],
  },
  {
    view: "git-settings",
    entries: [
      [
        "git.scanDepth",
        "field",
        "settings.gitScanDepthLabel",
        "Repository scan depth",
        [],
        ["scan", "扫描深度"],
      ],
      [
        "git.ignoredFolders",
        "field",
        "settings.gitIgnoredFoldersLabel",
        "Ignored folders",
        [],
        ["ignore", "忽略目录", "node_modules"],
      ],
      [
        "git.changeDebounce",
        "field",
        "settings.gitChangeDebounceLabel",
        "Change detection debounce (ms)",
        [],
        ["debounce", "防抖", "变更检测"],
      ],
      [
        "git.remotePoll",
        "field",
        "settings.gitRemotePollLabel",
        "Remote repo poll interval (ms)",
        [],
        ["poll", "轮询", "远程仓库"],
      ],
      [
        "git.statusLimit",
        "field",
        "settings.gitStatusLimitLabel",
        "Change list limit",
        [],
        ["limit", "变更列表上限"],
      ],
      [
        "git.autoRefresh",
        "field",
        "settings.gitAutoRefreshLabel",
        "Auto refresh on file changes",
        [],
        ["auto refresh", "自动刷新"],
      ],
      [
        "git.confirmPullPush",
        "field",
        "settings.gitConfirmPullPushLabel",
        "Confirm before pull / push",
        [],
        ["confirm", "拉取", "推送"],
      ],
    ],
  },
  {
    view: "system-prompt-settings",
    entries: [
      [
        "systemPrompt.manage",
        "section",
        "settings.systemPromptManualTitle",
        "Manage prompts",
        [],
        ["manage prompts", "提示词管理"],
      ],
      [
        "systemPrompt.list",
        "section",
        "settings.systemPromptListTitle",
        "Prompt list",
        [],
        ["prompt list", "提示词列表"],
      ],
      [
        "systemPrompt.editor",
        "section",
        "settings.systemPromptEditorTitle",
        "Prompt editor",
        [],
        ["prompt editor", "提示词编辑器"],
      ],
      [
        "systemPrompt.name",
        "field",
        "settings.systemPromptName",
        "Prompt name",
        [],
        ["prompt name", "提示词名称"],
      ],
      [
        "systemPrompt.content",
        "field",
        "settings.systemPromptContent",
        "Prompt content",
        [],
        ["prompt content", "提示词内容"],
      ],
    ],
  },
  {
    view: "personalization-settings",
    entries: [
      [
        "personalization.tab.global",
        "tab",
        "personalization.globalTitle",
        "Global rules",
        [],
        ["global rules", "全局规则", "ROLE.md"],
      ],
      [
        "personalization.tab.project",
        "tab",
        "personalization.projectTitle",
        "Project rules",
        [],
        ["project rules", "项目规则", "ROLE.md"],
      ],
      [
        "personalization.globalScopeNote",
        "field",
        "personalization.globalScopeNote",
        "Global rules are saved to ~/.snow/ROLE.md and apply to every project.",
        ["personalization.tab.global"],
        ["role.md", "全局规则路径"],
      ],
      [
        "personalization.globalPlaceholder",
        "field",
        "personalization.globalPlaceholder",
        "Enter global rules here, e.g. role definition, output style, coding conventions...",
        ["personalization.tab.global"],
        ["角色设定", "输出风格", "编码规范"],
      ],
      [
        "personalization.includeGlobal",
        "field",
        "personalization.includeGlobalTitle",
        "Load global rules",
        ["personalization.tab.project"],
        ["加载全局规则", "继承全局规则"],
      ],
      [
        "personalization.currentProject",
        "field",
        "personalization.currentProject",
        "Current project",
        ["personalization.tab.project"],
        ["当前项目"],
      ],
      [
        "personalization.projectPlaceholder",
        "field",
        "personalization.projectPlaceholder",
        "Enter rules for this project here, e.g. code style, architecture conventions, tech stack notes...",
        ["personalization.tab.project"],
        ["code style", "架构约定", "技术栈"],
      ],
      [
        "personalization.rulePriority",
        "section",
        "personalization.priorityTitle",
        "Rule priority",
        [],
        ["rule priority", "规则优先级"],
      ],
      [
        "personalization.loadOrder",
        "section",
        "personalization.loadOrder",
        "Load order",
        [],
        ["load order", "加载顺序"],
      ],
    ],
  },
  {
    view: "custom-headers-settings",
    entries: [
      [
        "customHeaders.manage",
        "section",
        "settings.customHeadersManualTitle",
        "Manage request header schemes",
        [],
        ["header schemes", "自定义请求头"],
      ],
      [
        "customHeaders.schemeCount",
        "field",
        "settings.customHeadersSchemeCount",
        "Schemes",
        [],
        ["schemes", "方案数量"],
      ],
      [
        "customHeaders.activeScheme",
        "field",
        "settings.customHeadersActiveScheme",
        "Active scheme",
        [],
        ["active scheme", "生效方案"],
      ],
      [
        "customHeaders.headerCount",
        "field",
        "settings.customHeadersHeaderCount",
        "Headers",
        [],
        ["headers", "请求头数量"],
      ],
      [
        "customHeaders.list",
        "section",
        "settings.customHeadersListTitle",
        "Header schemes",
        [],
        ["header schemes", "方案列表"],
      ],
      [
        "customHeaders.editor",
        "section",
        "settings.customHeadersEditorTitle",
        "Scheme editor",
        [],
        ["scheme editor", "方案编辑器"],
      ],
      [
        "customHeaders.schemeName",
        "field",
        "settings.customHeadersSchemeName",
        "Scheme name",
        [],
        ["scheme name", "方案名称"],
      ],
      [
        "customHeaders.headerName",
        "field",
        "settings.customHeadersHeaderName",
        "Header name",
        [],
        ["header name", "请求头名称"],
      ],
      [
        "customHeaders.headerValue",
        "field",
        "settings.customHeadersHeaderValue",
        "Header value",
        [],
        ["header value", "请求头值"],
      ],
      [
        "customHeaders.variables",
        "field",
        "settings.customHeadersVariablesLabel",
        "Available variables",
        [],
        ["variables", "变量", "session_id"],
      ],
    ],
  },
  {
    view: "mcp-settings",
    entries: [
      [
        "mcp.tab.global",
        "tab",
        "settings.mcpTabGlobal",
        "Global",
        [],
        ["global", "全局"],
      ],
      [
        "mcp.tab.project",
        "tab",
        "settings.mcpTabProject",
        "Project",
        [],
        ["project", "项目"],
      ],
      [
        "mcp.section.globalServers",
        "section",
        "settings.mcpGlobalListTitle",
        "Global MCP servers",
        ["mcp.tab.global"],
        ["global servers", "全局服务器"],
      ],
      [
        "mcp.section.projectServers",
        "section",
        "settings.mcpProjectListTitle",
        "Project MCP servers",
        ["mcp.tab.project"],
        ["project servers", "项目服务器"],
      ],
      [
        "mcp.tab.editorForm",
        "tab",
        "settings.mcpEditForm",
        "Form",
        [],
        ["form", "表单模式"],
      ],
      ["mcp.tab.editorJson", "tab", null, "JSON", [], ["json", "json 编辑"]],
      [
        "mcp.field.serverName",
        "field",
        "settings.mcpServerName",
        "Server name",
        ["mcp.tab.editorForm"],
        ["name", "服务器名称"],
      ],
      [
        "mcp.field.transport",
        "field",
        "settings.mcpTransportType",
        "Transport",
        ["mcp.tab.editorForm"],
        ["transport", "stdio", "传输方式"],
      ],
      [
        "mcp.field.timeoutMs",
        "field",
        "settings.mcpTimeoutMs",
        "Timeout (ms)",
        ["mcp.tab.editorForm"],
        ["timeout", "超时"],
      ],
      [
        "mcp.field.url",
        "field",
        "settings.mcpUrl",
        "URL",
        ["mcp.tab.editorForm"],
        ["url", "地址"],
      ],
      [
        "mcp.field.command",
        "field",
        "settings.mcpCommand",
        "Command",
        ["mcp.tab.editorForm"],
        ["command", "命令"],
      ],
      [
        "mcp.field.enabled",
        "field",
        "settings.mcpServerEnabled",
        "Enable server",
        ["mcp.tab.editorForm"],
        ["enable", "启用"],
      ],
      [
        "mcp.section.args",
        "section",
        "settings.mcpArgs",
        "Args",
        ["mcp.tab.editorForm"],
        ["args", "参数"],
      ],
      [
        "mcp.section.environment",
        "section",
        "settings.mcpEnvironment",
        "Environment",
        ["mcp.tab.editorForm"],
        ["env", "环境变量"],
      ],
      [
        "mcp.section.headers",
        "section",
        "settings.mcpHeaders",
        "Headers",
        ["mcp.tab.editorForm"],
        ["headers", "请求头"],
      ],
      [
        "mcp.section.tools",
        "section",
        "settings.mcpToolDetailsTitle",
        "Server tools",
        ["mcp.tab.editorForm"],
        ["tools", "工具列表"],
      ],
      [
        "mcp.field.toolFilter",
        "field",
        "settings.mcpToolFilterPlaceholder",
        "Filter tools by name or description",
        ["mcp.tab.editorForm"],
        ["tool filter", "筛选工具"],
      ],
    ],
  },
  {
    view: "lsp-settings",
    entries: [
      [
        "lsp.tab.global",
        "tab",
        "settings.lspTabGlobal",
        "Global",
        [],
        ["global", "全局"],
      ],
      [
        "lsp.tab.project",
        "tab",
        "settings.lspTabProject",
        "Project",
        [],
        ["project", "项目"],
      ],
      [
        "lsp.section.stackDetect",
        "section",
        "settings.lspStackDetectTitle",
        "Detected project stack",
        ["lsp.tab.project"],
        ["stack", "技术栈检测"],
      ],
      [
        "lsp.section.serverList",
        "section",
        "settings.lspServerListTitle",
        "Language servers",
        ["lsp.tab.global"],
        ["language server", "语言服务器"],
      ],
      [
        "lsp.section.args",
        "section",
        "settings.lspArgs",
        "Args",
        [],
        ["args", "参数"],
      ],
      [
        "lsp.section.fileExtensions",
        "section",
        "settings.lspFileExtensions",
        "File extensions",
        [],
        ["extensions", "文件后缀"],
      ],
      [
        "lsp.field.language",
        "field",
        "settings.lspLanguage",
        "Language",
        [],
        ["language", "语言"],
      ],
      [
        "lsp.field.command",
        "field",
        "settings.lspCommand",
        "Command",
        [],
        ["command", "命令"],
      ],
      [
        "lsp.field.installCommand",
        "field",
        "settings.lspInstallCommand",
        "Install command (optional)",
        [],
        ["install", "安装命令"],
      ],
      [
        "lsp.field.initializationOptions",
        "field",
        "settings.lspInitializationOptions",
        "Initialization options JSON (optional)",
        [],
        ["initializationOptions", "初始化选项"],
      ],
      [
        "lsp.field.enabled",
        "field",
        "settings.lspServerEnabled",
        "Enable language server",
        [],
        ["enable", "启用"],
      ],
    ],
  },
  {
    view: "skills-settings",
    entries: [
      [
        "skills.tab.global",
        "tab",
        "settings.skillsTabGlobal",
        "Global",
        [],
        ["global", "全局"],
      ],
      [
        "skills.tab.project",
        "tab",
        "settings.skillsTabProject",
        "Project",
        [],
        ["project", "项目"],
      ],
      [
        "skills.section.install",
        "section",
        "settings.skillsInstallTitle",
        "Install from GitHub",
        [],
        ["install", "github", "安装技能"],
      ],
      [
        "skills.field.installUrl",
        "field",
        "settings.skillsInstallUrlLabel",
        "GitHub URL",
        [],
        ["url", "仓库地址"],
      ],
      [
        "skills.section.globalList",
        "section",
        "settings.skillsGlobalListTitle",
        "Global Skills",
        ["skills.tab.global"],
        ["skills list", "全局技能"],
      ],
      [
        "skills.section.projectList",
        "section",
        "settings.skillsProjectListTitle",
        "Project Skills",
        ["skills.tab.project"],
        ["skills list", "项目技能"],
      ],
      [
        "skills.field.enable",
        "field",
        "settings.skillsEnable",
        "Enable Skill",
        [],
        ["enable", "启用技能"],
      ],
      [
        "skills.field.disable",
        "field",
        "settings.skillsDisable",
        "Disable Skill",
        [],
        ["disable", "禁用技能"],
      ],
      [
        "skills.field.allowedTools",
        "field",
        "settings.skillsAllowedTools",
        "Allowed tools",
        [],
        ["allowed tools", "工具权限"],
      ],
    ],
  },
  {
    view: "sub-agent-settings",
    entries: [
      [
        "subAgent.tab.global",
        "tab",
        "settings.subAgentTabGlobal",
        "Global",
        [],
        ["global", "全局"],
      ],
      [
        "subAgent.tab.project",
        "tab",
        "settings.subAgentTabProject",
        "Project",
        [],
        ["project", "项目"],
      ],
      [
        "subAgent.section.manage",
        "section",
        "settings.subAgentManageTitle",
        "Manage sub-agents",
        ["subAgent.tab.global"],
        ["manage", "管理子代理"],
      ],
      [
        "subAgent.section.list",
        "section",
        "settings.subAgentListTitle",
        "Sub-agent list",
        ["subAgent.tab.global"],
        ["list", "子代理列表"],
      ],
      [
        "subAgent.field.name",
        "field",
        "settings.subAgentName",
        "Name",
        [],
        ["name", "名称"],
      ],
      [
        "subAgent.field.configProfile",
        "field",
        "settings.subAgentConfigProfile",
        "API and model",
        [],
        ["profile", "接口配置"],
      ],
      [
        "subAgent.field.followActiveProfile",
        "field",
        "settings.subAgentFollowActiveApiProfile",
        "Follow the parent conversation (recommended)",
        [],
        ["follow", "继承父会话"],
      ],
      [
        "subAgent.field.model",
        "field",
        "settings.subAgentModel",
        "Model",
        [],
        ["model", "模型"],
      ],
      [
        "subAgent.field.useProfileAdvancedModel",
        "field",
        "settings.subAgentUseProfileAdvancedModel",
        "Use the API profile's advanced model",
        [],
        ["advanced model", "高级模型"],
      ],
      [
        "subAgent.field.description",
        "field",
        "settings.subAgentDescription",
        "Description",
        [],
        ["description", "描述"],
      ],
      [
        "subAgent.field.systemPrompt",
        "field",
        "settings.subAgentSystemPrompt",
        "Sub-agent system prompt",
        [],
        ["system prompt", "系统提示词"],
      ],
      [
        "subAgent.field.tools",
        "field",
        "settings.subAgentTools",
        "MCP tools",
        [],
        ["mcp tools", "工具选择"],
      ],
    ],
  },
  {
    view: "sensitive-command-settings",
    entries: [
      [
        "sensitiveCommand.tab.rules",
        "tab",
        "settings.sensitiveCommandRulesTab",
        "Command rules",
        [],
        ["rules", "命令规则"],
      ],
      [
        "sensitiveCommand.tab.assist",
        "tab",
        "settings.sensitiveCommandAssistTitle",
        "Decision model assist",
        [],
        ["assist", "决策模型辅助"],
      ],
      [
        "sensitiveCommand.tab.global",
        "tab",
        "settings.sensitiveCommandTabGlobal",
        "Global",
        ["sensitiveCommand.tab.rules"],
        ["global", "全局"],
      ],
      [
        "sensitiveCommand.tab.project",
        "tab",
        "settings.sensitiveCommandTabProject",
        "Project",
        ["sensitiveCommand.tab.rules"],
        ["project", "项目"],
      ],
      [
        "sensitiveCommand.section.globalList",
        "section",
        "settings.sensitiveCommandGlobalListTitle",
        "Global sensitive command rules",
        ["sensitiveCommand.tab.rules", "sensitiveCommand.tab.global"],
        ["global rules", "全局规则"],
      ],
      [
        "sensitiveCommand.section.projectList",
        "section",
        "settings.sensitiveCommandProjectListTitle",
        "Effective project rules",
        ["sensitiveCommand.tab.rules", "sensitiveCommand.tab.project"],
        ["project rules", "项目规则"],
      ],
      [
        "sensitiveCommand.field.pattern",
        "field",
        "settings.sensitiveCommandPattern",
        "Command pattern",
        [],
        ["pattern", "正则"],
      ],
      [
        "sensitiveCommand.field.description",
        "field",
        "settings.sensitiveCommandDescription",
        "Description",
        [],
        ["description", "描述"],
      ],
      [
        "sensitiveCommand.field.enabled",
        "field",
        "settings.sensitiveCommandEnabled",
        "Enable rule",
        [],
        ["enable", "启用规则"],
      ],
      [
        "sensitiveCommand.field.assistToggle",
        "field",
        "settings.sensitiveCommandAssistToggle",
        "Enable decision model assist",
        ["sensitiveCommand.tab.assist"],
        ["enable assist", "启用辅助"],
      ],
      [
        "sensitiveCommand.field.assistModel",
        "field",
        "settings.sensitiveCommandAssistModel",
        "Decision model",
        ["sensitiveCommand.tab.assist"],
        ["decision model", "决策模型"],
      ],
      [
        "sensitiveCommand.field.assistDelegate",
        "field",
        "settings.sensitiveCommandAssistDelegate",
        "Let the decision model handle the gate",
        ["sensitiveCommand.tab.assist"],
        ["delegate", "自动放行"],
      ],
    ],
  },
  {
    view: "custom-commands-settings",
    entries: [
      [
        "customCommand.tab.global",
        "tab",
        "settings.customCommandsGlobalTab",
        "Global",
        [],
        ["global", "全局"],
      ],
      [
        "customCommand.tab.project",
        "tab",
        "settings.customCommandsProjectTab",
        "Current project",
        [],
        ["project", "当前项目"],
      ],
      [
        "customCommand.field.name",
        "field",
        "settings.customCommandName",
        "Command name",
        [],
        ["name", "slash", "命令名"],
      ],
      [
        "customCommand.field.type",
        "field",
        "settings.customCommandType",
        "Type",
        [],
        ["type", "类型"],
      ],
      [
        "customCommand.option.typePrompt",
        "field",
        "settings.customCommandTypePrompt",
        "Prompt (send to AI)",
        [],
        ["prompt", "发送给 AI"],
      ],
      [
        "customCommand.option.typeBash",
        "field",
        "settings.customCommandTypeBash",
        "Bash (run shell command)",
        [],
        ["bash", "shell", "执行命令"],
      ],
      [
        "customCommand.field.prompt",
        "field",
        "settings.customCommandPromptContent",
        "Prompt",
        [],
        ["prompt content", "提示词内容"],
      ],
      [
        "customCommand.field.command",
        "field",
        "settings.customCommandBashContent",
        "Command",
        [],
        ["command content", "命令内容"],
      ],
      [
        "customCommand.field.description",
        "field",
        "settings.customCommandDescription",
        "Description",
        [],
        ["description", "描述"],
      ],
      [
        "customCommand.field.enabled",
        "field",
        "settings.customCommandEnabled",
        "Enabled",
        [],
        ["enable", "启用"],
      ],
    ],
  },
  {
    view: "hooks-settings",
    entries: [
      [
        "hooks.tab.global",
        "tab",
        "settings.hooksTabGlobal",
        "Global",
        [],
        ["global", "全局"],
      ],
      [
        "hooks.tab.project",
        "tab",
        "settings.hooksTabProject",
        "Project",
        [],
        ["project", "项目"],
      ],
      [
        "hooks.section.globalList",
        "section",
        "settings.hooksGlobalListTitle",
        "Global hook configurations",
        ["hooks.tab.global"],
        ["global hooks", "全局钩子"],
      ],
      [
        "hooks.section.projectList",
        "section",
        "settings.hooksProjectListTitle",
        "Project hook configurations",
        ["hooks.tab.project"],
        ["project hooks", "项目钩子"],
      ],
      [
        "hooks.field.hookType",
        "field",
        "settings.hookType",
        "Hook type",
        [],
        ["hook type", "钩子类型", "生命周期"],
      ],
      [
        "hooks.field.scope",
        "field",
        "settings.hookScope",
        "Scope",
        [],
        ["scope", "作用域"],
      ],
      [
        "hooks.field.ruleDescription",
        "field",
        "settings.hooksRuleDescription",
        "Description",
        [],
        ["description", "规则描述"],
      ],
      [
        "hooks.field.matcher",
        "field",
        "settings.hooksMatcher",
        "Tool matcher",
        [],
        ["matcher", "工具匹配"],
      ],
      [
        "hooks.field.actionType",
        "field",
        "settings.hooksActionType",
        "Action type",
        [],
        ["action type", "动作类型"],
      ],
      [
        "hooks.field.actionEnabled",
        "field",
        "settings.hooksActionEnabled",
        "Enabled",
        [],
        ["enable", "启用动作"],
      ],
      [
        "hooks.field.actionTimeout",
        "field",
        "settings.hooksActionTimeout",
        "Timeout (ms)",
        [],
        ["timeout", "超时"],
      ],
      [
        "hooks.field.actionCommand",
        "field",
        "settings.hooksActionCommand",
        "Command",
        [],
        ["command", "执行命令"],
      ],
      [
        "hooks.field.actionPrompt",
        "field",
        "settings.hooksActionPrompt",
        "Prompt",
        [],
        ["prompt", "提示词"],
      ],
      [
        "hooks.field.actionContent",
        "field",
        "settings.hooksActionContent",
        "Context content",
        [],
        ["context", "上下文内容"],
      ],
    ],
  },
  {
    view: "theme-settings",
    entries: [
      [
        "theme.mode",
        "section",
        "settings.themeMode",
        "Appearance mode",
        [],
        ["appearance", "外观模式", "暗色"],
      ],
      [
        "theme.mode.system",
        "field",
        "settings.themeModeSystem",
        "System",
        [],
        ["system", "跟随系统"],
      ],
      [
        "theme.mode.light",
        "field",
        "settings.themeModeLight",
        "Light",
        [],
        ["light", "浅色"],
      ],
      [
        "theme.mode.dark",
        "field",
        "settings.themeModeDark",
        "Dark",
        [],
        ["dark", "深色"],
      ],
      [
        "theme.presets",
        "section",
        "settings.themePresets",
        "Preset themes",
        [],
        ["preset", "预设主题", "配色"],
      ],
      [
        "theme.preset.snow",
        "field",
        "settings.themePresetSnow",
        "Snow",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.midnightBlue",
        "field",
        "settings.themePresetMidnightBlue",
        "Midnight Blue",
        [],
        ["preset", "午夜蓝"],
      ],
      [
        "theme.preset.forestGreen",
        "field",
        "settings.themePresetForestGreen",
        "Forest Green",
        [],
        ["preset", "森林绿"],
      ],
      [
        "theme.preset.rosePink",
        "field",
        "settings.themePresetRosePink",
        "Rose Pink",
        [],
        ["preset", "玫瑰粉"],
      ],
      [
        "theme.preset.solarized",
        "field",
        "settings.themePresetSolarized",
        "Solarized",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.nord",
        "field",
        "settings.themePresetNord",
        "Nord",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.dracula",
        "field",
        "settings.themePresetDracula",
        "Dracula",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.tokyoNight",
        "field",
        "settings.themePresetTokyoNight",
        "Tokyo Night",
        [],
        ["preset", "东京夜"],
      ],
      [
        "theme.preset.github",
        "field",
        "settings.themePresetGithub",
        "GitHub",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.google",
        "field",
        "settings.themePresetGoogle",
        "Google",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.gruvbox",
        "field",
        "settings.themePresetGruvbox",
        "Gruvbox",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.cream",
        "field",
        "settings.themePresetCream",
        "Cream",
        [],
        ["preset", "奶油"],
      ],
      [
        "theme.preset.win95",
        "field",
        "settings.themePresetWin95",
        "Win95",
        [],
        ["preset", "复古"],
      ],
      [
        "theme.preset.cyberpunk",
        "field",
        "settings.themePresetCyberpunk",
        "Cyberpunk",
        [],
        ["preset", "赛博朋克"],
      ],
      [
        "theme.preset.notion",
        "field",
        "settings.themePresetNotion",
        "Notion",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.compact",
        "field",
        "settings.themePresetCompact",
        "Horizon",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.preset.tesseract",
        "field",
        "settings.themePresetTesseract",
        "Tesseract",
        [],
        ["preset", "预设"],
      ],
      [
        "theme.custom",
        "section",
        "settings.themeCustomTitle",
        "Custom theme",
        [],
        ["custom theme", "自定义主题", "调色板"],
      ],
      [
        "theme.custom.lightPalette",
        "tab",
        "settings.themeTabLight",
        "Light palette",
        [],
        ["light palette", "浅色调色板"],
      ],
      [
        "theme.custom.darkPalette",
        "tab",
        "settings.themeTabDark",
        "Dark palette",
        [],
        ["dark palette", "深色调色板"],
      ],
      [
        "theme.custom.groupBackground",
        "section",
        "settings.themeGroupBackground",
        "Background",
        ["theme.custom.lightPalette"],
        ["background", "背景色"],
      ],
      [
        "theme.custom.groupText",
        "section",
        "settings.themeGroupText",
        "Text",
        ["theme.custom.lightPalette"],
        ["text color", "文字颜色"],
      ],
      [
        "theme.custom.groupBorder",
        "section",
        "settings.themeGroupBorder",
        "Border",
        ["theme.custom.lightPalette"],
        ["border color", "边框颜色"],
      ],
      [
        "theme.custom.groupAccent",
        "section",
        "settings.themeGroupAccent",
        "Accent colors",
        ["theme.custom.lightPalette"],
        ["accent", "强调色"],
      ],
      [
        "theme.custom.groupOther",
        "section",
        "settings.themeGroupOther",
        "Other",
        ["theme.custom.lightPalette"],
        ["focus ring", "其他颜色"],
      ],
      [
        "theme.background",
        "section",
        "settings.themeBackgroundTitle",
        "Background image",
        [],
        ["background image", "背景图", "壁纸"],
      ],
      [
        "theme.background.opacity",
        "field",
        "settings.themeBackgroundOpacity",
        "Opacity",
        [],
        ["opacity", "透明度"],
      ],
      [
        "theme.background.blur",
        "field",
        "settings.themeBackgroundBlur",
        "Blur",
        [],
        ["blur", "模糊"],
      ],
      [
        "theme.font",
        "section",
        "settings.themeFontTitle",
        "Font",
        [],
        ["font family", "字体"],
      ],
      [
        "theme.streamCursor",
        "section",
        "settings.themeStreamCursorTitle",
        "Streaming indicator",
        [],
        ["stream cursor", "流式光标"],
      ],
      [
        "theme.streamCursor.typeDot",
        "field",
        "settings.themeStreamCursorTypeDot",
        "Pulsing dot",
        [],
        ["dot", "脉冲点"],
      ],
      [
        "theme.streamCursor.typeLucide",
        "field",
        "settings.themeStreamCursorTypeLucide",
        "Built-in icon",
        [],
        ["built-in icon", "内置图标"],
      ],
      [
        "theme.streamCursor.typeCustom",
        "field",
        "settings.themeStreamCursorTypeCustom",
        "Custom SVG",
        [],
        ["custom svg", "自定义 svg"],
      ],
      [
        "theme.streamCursor.size",
        "field",
        "settings.themeStreamCursorSize",
        "Icon size",
        [],
        ["icon size", "图标尺寸"],
      ],
    ],
  },
  {
    view: "terminal-settings",
    entries: [
      [
        "terminal.shell",
        "section",
        "settings.terminalSectionShell",
        "Shell",
        [],
        ["shell", "终端", "命令行"],
      ],
      [
        "terminal.shellPath",
        "field",
        "settings.terminalShellPathPlaceholder",
        "Leave empty to auto-detect",
        [],
        ["shell path", "自动检测", "powershell"],
      ],
      [
        "terminal.font",
        "section",
        "settings.terminalSectionFont",
        "Font",
        [],
        ["font", "字体"],
      ],
      [
        "terminal.fontFamily",
        "field",
        "settings.terminalFontFamily",
        "Font family",
        [],
        ["consolas", "字体族"],
      ],
      [
        "terminal.fontSize",
        "field",
        "settings.terminalFontSize",
        "Font size",
        [],
        ["font size", "字号"],
      ],
      [
        "terminal.fontWeight",
        "field",
        "settings.terminalFontWeight",
        "Font weight",
        [],
        ["font weight", "字重"],
      ],
      [
        "terminal.lineHeight",
        "field",
        "settings.terminalLineHeight",
        "Line height",
        [],
        ["line height", "行高"],
      ],
      [
        "terminal.rendering",
        "section",
        "settings.terminalSectionRendering",
        "Rendering",
        [],
        ["rendering", "渲染"],
      ],
      [
        "terminal.gpuRendering",
        "field",
        "settings.terminalGpuRendering",
        "GPU rendering (WebGL)",
        [],
        ["gpu", "webgl", "硬件加速"],
      ],
    ],
  },
  {
    view: "browser-settings",
    entries: [
      [
        "browser.tab.settings",
        "tab",
        "settings.browserSettingsTitle",
        "Browser settings",
        [],
        ["browser", "浏览器设置"],
      ],
      [
        "browser.tab.devices",
        "tab",
        "settings.browserDevicesTitle",
        "Display size devices",
        [],
        ["device", "显示尺寸", "ua"],
      ],
      [
        "browser.tab.userscripts",
        "tab",
        "userscripts.title",
        "Userscripts",
        [],
        ["油猴脚本", "tampermonkey", "greasyfork"],
      ],
      [
        "browser.homepage",
        "section",
        "settings.browserHomepage",
        "Homepage",
        ["browser.tab.settings"],
        ["homepage", "起始页", "主页"],
      ],
      [
        "browser.homepage.url",
        "field",
        "settings.browserHomepagePlaceholder",
        "Enter URL, leave empty for blank page",
        ["browser.tab.settings"],
        ["url", "空白页"],
      ],
      [
        "browser.import",
        "section",
        "settings.browserImport",
        "Import",
        ["browser.tab.settings"],
        ["import", "导入"],
      ],
      [
        "browser.passwords",
        "section",
        "settings.browserPasswords",
        "Passwords",
        ["browser.tab.settings"],
        ["passwords", "密码管理"],
      ],
      [
        "browser.passwords.manage",
        "section",
        "settings.browserPasswordsManualTitle",
        "Manage saved passwords",
        ["browser.tab.settings"],
        ["vault", "已保存密码"],
      ],
      [
        "browser.passwords.site",
        "field",
        "settings.browserPasswordSite",
        "Site",
        ["browser.tab.settings"],
        ["site", "站点"],
      ],
      [
        "browser.passwords.username",
        "field",
        "settings.browserPasswordUser",
        "Username",
        ["browser.tab.settings"],
        ["username", "用户名"],
      ],
      [
        "browser.passwords.value",
        "field",
        "settings.browserPasswordValue",
        "Password",
        ["browser.tab.settings"],
        ["password", "密码值"],
      ],
      [
        "browser.bookmarks",
        "section",
        "settings.browserBookmarks",
        "Bookmarks",
        ["browser.tab.settings"],
        ["bookmarks", "书签"],
      ],
      [
        "browser.bookmarks.manage",
        "section",
        "settings.browserBookmarksManageTitle",
        "Manage bookmarks",
        ["browser.tab.settings"],
        ["书签管理", "书签栏"],
      ],
      [
        "browser.bookmarks.title",
        "field",
        "settings.browserBookmarkTitle",
        "Title",
        ["browser.tab.settings"],
        ["bookmark title", "书签标题"],
      ],
      [
        "browser.bookmarks.url",
        "field",
        "settings.browserBookmarkUrl",
        "URL",
        ["browser.tab.settings"],
        ["bookmark url", "书签地址"],
      ],
      [
        "browser.bookmarks.folder",
        "field",
        "settings.browserBookmarkFolder",
        "Folder",
        ["browser.tab.settings"],
        ["folder", "书签文件夹"],
      ],
      [
        "browser.devices.custom",
        "section",
        "settings.browserDevicesCustomTitle",
        "Custom devices",
        ["browser.tab.devices"],
        ["自定义设备"],
      ],
      [
        "browser.devices.builtin",
        "section",
        "settings.browserDevicesBuiltinTitle",
        "Preset devices",
        ["browser.tab.devices"],
        ["内置设备", "预设设备"],
      ],
      [
        "browser.devices.name",
        "field",
        "settings.browserDeviceNamePlaceholder",
        "Device name",
        ["browser.tab.devices"],
        ["设备名称"],
      ],
      [
        "browser.devices.width",
        "field",
        "settings.browserDeviceWidth",
        "Width",
        ["browser.tab.devices"],
        ["viewport", "视口宽度"],
      ],
      [
        "browser.devices.height",
        "field",
        "settings.browserDeviceHeight",
        "Height",
        ["browser.tab.devices"],
        ["viewport", "视口高度"],
      ],
      [
        "browser.devices.dpr",
        "field",
        "settings.browserDeviceDpr",
        "DPR",
        ["browser.tab.devices"],
        ["像素比"],
      ],
      [
        "browser.devices.mobile",
        "field",
        "settings.browserDeviceMobile",
        "Mobile",
        ["browser.tab.devices"],
        ["移动端", "手机"],
      ],
      [
        "browser.devices.desktop",
        "field",
        "settings.browserDeviceDesktop",
        "Desktop",
        ["browser.tab.devices"],
        ["桌面端"],
      ],
      [
        "browser.devices.ua",
        "field",
        "settings.browserDeviceUaPlaceholder",
        "User agent string (empty = keep default)",
        ["browser.tab.devices"],
        ["user agent", "ua"],
      ],
      [
        "browser.devices.search",
        "field",
        "settings.browserDeviceSearchPlaceholder",
        "Search devices",
        ["browser.tab.devices"],
        ["搜索设备"],
      ],
      [
        "browser.userscripts.installedTab",
        "tab",
        "userscripts.installedTab",
        "Installed",
        ["browser.tab.userscripts"],
        ["已安装脚本"],
      ],
      [
        "browser.userscripts.searchTab",
        "tab",
        "userscripts.searchTab",
        "Search & Download",
        ["browser.tab.userscripts"],
        ["搜索下载"],
      ],
      [
        "browser.userscripts.name",
        "field",
        "userscripts.name",
        "Name",
        ["browser.tab.userscripts", "browser.userscripts.installedTab"],
        ["脚本名称"],
      ],
      [
        "browser.userscripts.matches",
        "field",
        "userscripts.matches",
        "Matches",
        ["browser.tab.userscripts", "browser.userscripts.installedTab"],
        ["匹配规则", "match"],
      ],
      [
        "browser.userscripts.runAt",
        "field",
        "userscripts.runAt",
        "Run at",
        ["browser.tab.userscripts", "browser.userscripts.installedTab"],
        ["执行时机"],
      ],
      [
        "browser.userscripts.enable",
        "field",
        "userscripts.enable",
        "Enable",
        ["browser.tab.userscripts", "browser.userscripts.installedTab"],
        ["启用脚本"],
      ],
      [
        "browser.userscripts.searchBox",
        "field",
        "userscripts.searchPlaceholder",
        "Search Greasy Fork...",
        ["browser.tab.userscripts", "browser.userscripts.searchTab"],
        ["greasy fork", "脚本搜索"],
      ],
    ],
  },
  {
    view: "keyboard-shortcuts-settings",
    entries: [
      [
        "shortcuts.list",
        "section",
        "settings.shortcutListTitle",
        "Shortcut list",
        [],
        ["shortcut", "快捷键列表"],
      ],
      [
        "shortcuts.enabled",
        "field",
        "settings.shortcutEnabled",
        "Enabled",
        [],
        ["enabled", "启用快捷键"],
      ],
      [
        "shortcuts.foregroundOnly",
        "field",
        "settings.shortcutForegroundOnly",
        "Foreground only",
        [],
        ["仅前台", "窗口聚焦"],
      ],
      [
        "shortcuts.cancelSession",
        "field",
        "settings.shortcutCancelSession",
        "Interrupt current session",
        [],
        ["中断", "停止生成"],
      ],
      [
        "shortcuts.openSearch",
        "field",
        "settings.shortcutOpenSearch",
        "Open global search",
        [],
        ["全局搜索"],
      ],
      [
        "shortcuts.openMemo",
        "field",
        "settings.shortcutOpenMemo",
        "Open memos",
        [],
        ["备忘录", "笔记"],
      ],
      [
        "shortcuts.openTodo",
        "field",
        "settings.shortcutOpenTodo",
        "Open todo list",
        [],
        ["待办", "任务列表"],
      ],
      [
        "shortcuts.cycleProject",
        "field",
        "settings.shortcutCycleProject",
        "Cycle through projects",
        [],
        ["切换项目"],
      ],
      [
        "shortcuts.openExplorer",
        "field",
        "settings.shortcutOpenExplorer",
        "Open current project explorer",
        [],
        ["文件浏览器", "项目资源"],
      ],
      [
        "shortcuts.cycleApiProfile",
        "field",
        "settings.shortcutCycleApiProfile",
        "Open API provider picker",
        [],
        ["供应商切换", "接口配置"],
      ],
      [
        "shortcuts.toggleWindow",
        "field",
        "settings.shortcutToggleWindow",
        "Show/hide main window",
        [],
        ["主窗口", "呼出窗口"],
      ],
      [
        "shortcuts.togglePet",
        "field",
        "settings.shortcutTogglePet",
        "Show/hide desktop pet",
        [],
        ["桌宠", "宠物"],
      ],
      [
        "shortcuts.focusInput",
        "field",
        "settings.shortcutFocusInput",
        "Focus chat input",
        [],
        ["聚焦输入框"],
      ],
      [
        "shortcuts.toggleSidebar",
        "field",
        "settings.shortcutToggleSidebar",
        "Collapse/expand left sidebar",
        [],
        ["左侧边栏", "收起侧栏"],
      ],
      [
        "shortcuts.toggleRightPanel",
        "field",
        "settings.shortcutToggleRightPanel",
        "Collapse/expand right panel",
        [],
        ["右侧面板", "收起右栏"],
      ],
    ],
  },
  {
    view: "pets-settings",
    entries: [
      [
        "pets.manage",
        "section",
        "settings.petsManageTitle",
        "Manage pets",
        [],
        ["宠物管理", "桌面宠物"],
      ],
      [
        "pets.activeSection",
        "section",
        "settings.petsActiveSection",
        "Active pet",
        [],
        ["当前宠物"],
      ],
      [
        "pets.wake",
        "field",
        "settings.petsWake",
        "Wake up pet",
        [],
        ["唤醒宠物", "显示宠物"],
      ],
      [
        "pets.dismiss",
        "field",
        "settings.petsDismiss",
        "Put pet away",
        [],
        ["收起宠物", "隐藏宠物"],
      ],
      [
        "pets.scale",
        "field",
        "settings.petsScale",
        "Size",
        [],
        ["宠物大小", "缩放"],
      ],
      [
        "pets.installedSection",
        "section",
        "settings.petsInstalledSection",
        "Installed pets",
        [],
        ["已安装宠物", "宠物列表"],
      ],
    ],
  },
  {
    view: "privacy-settings",
    entries: [
      [
        "privacy.config",
        "section",
        "settings.privacyManualTitle",
        "Filter configuration",
        [],
        ["过滤配置"],
      ],
      [
        "privacy.enabled",
        "field",
        "settings.privacyEnable",
        "Enable privacy filter",
        [],
        ["隐私过滤", "脱敏"],
      ],
      [
        "privacy.mode",
        "section",
        "settings.privacyMode",
        "Filter mode",
        [],
        ["过滤模式"],
      ],
      [
        "privacy.mode.local",
        "field",
        "settings.privacyModeLocal",
        "Local rules",
        [],
        ["本地规则"],
      ],
      [
        "privacy.mode.api",
        "field",
        "settings.privacyModeApi",
        "Online API",
        [],
        ["在线接口", "远程过滤"],
      ],
      [
        "privacy.apiConfig",
        "section",
        "settings.privacyApiConfig",
        "API configuration",
        [],
        ["接口配置"],
      ],
      [
        "privacy.api.url",
        "field",
        "settings.privacyUrlLabel",
        "URL",
        [],
        ["接口地址"],
      ],
      [
        "privacy.api.key",
        "field",
        "settings.privacyApiKeyLabel",
        "API key (optional)",
        [],
        ["密钥", "token"],
      ],
      [
        "privacy.api.model",
        "field",
        "settings.privacyModelLabel",
        "Model",
        [],
        ["模型"],
      ],
      [
        "privacy.tools",
        "section",
        "settings.privacyToolResults",
        "Tool results to filter",
        [],
        ["工具结果", "过滤范围"],
      ],
      [
        "privacy.tool.filesystem",
        "field",
        "settings.privacyToolFilesystem",
        "Filesystem",
        [],
        ["文件系统"],
      ],
      [
        "privacy.tool.search",
        "field",
        "settings.privacyToolSearch",
        "Search",
        [],
        ["grep", "代码搜索"],
      ],
      [
        "privacy.tool.terminal",
        "field",
        "settings.privacyToolTerminal",
        "Terminal",
        [],
        ["终端命令"],
      ],
      [
        "privacy.tool.codebase",
        "field",
        "settings.privacyToolCodebase",
        "Codebase",
        [],
        ["代码库", "索引搜索"],
      ],
      [
        "privacy.tool.websearch",
        "field",
        "settings.privacyToolWebsearch",
        "Web search",
        [],
        ["联网搜索"],
      ],
      [
        "privacy.tool.webfetch",
        "field",
        "settings.privacyToolWebfetch",
        "Web fetch",
        [],
        ["网页抓取"],
      ],
    ],
  },
  {
    view: "remote-control-settings",
    entries: [
      [
        "remote.tab.lan",
        "tab",
        "remoteControl.tabLan",
        "局域网",
        [],
        ["lan", "内网"],
      ],
      [
        "remote.tab.wan",
        "tab",
        "remoteControl.tabWan",
        "公网",
        [],
        ["wan", "外网", "隧道"],
      ],
      [
        "remote.master.enable",
        "field",
        "remoteControl.enableTitle",
        "启用手机远控",
        [],
        ["手机远控", "总开关"],
      ],
      [
        "remote.lan.port",
        "field",
        "remoteControl.portLabel",
        "局域网监听端口",
        ["remote.tab.lan"],
        ["port", "监听端口"],
      ],
      [
        "remote.lan.token",
        "section",
        "remoteControl.lanTokenTitle",
        "局域网令牌",
        ["remote.tab.lan"],
        ["token", "固定令牌"],
      ],
      [
        "remote.lan.address",
        "field",
        "remoteControl.lanAddress",
        "局域网地址",
        ["remote.tab.lan"],
        ["地址", "配对链接"],
      ],
      [
        "remote.wan.tunnel",
        "section",
        "remoteControl.tunnelTitle",
        "自建服务器公网连接",
        ["remote.tab.wan"],
        ["tunnel", "frp", "公网连接"],
      ],
      [
        "remote.wan.frpTunnel",
        "field",
        "remoteControl.frpTunnel",
        "FRP 隧道",
        ["remote.tab.wan"],
        ["frp", "隧道状态"],
      ],
      [
        "remote.wan.httpsProbe",
        "field",
        "remoteControl.httpsProbe",
        "HTTPS 探测",
        ["remote.tab.wan"],
        ["https", "探测"],
      ],
      [
        "remote.wan.configured",
        "section",
        "remoteControl.configuredTitle",
        "已保存的公网配置",
        ["remote.tab.wan"],
        ["公网配置"],
      ],
      [
        "remote.wan.serverAddr",
        "field",
        "remoteControl.frpServerAddr",
        "FRP 服务器地址",
        ["remote.tab.wan"],
        ["frp server", "服务器地址"],
      ],
      [
        "remote.wan.remotePort",
        "field",
        "remoteControl.frpRemotePort",
        "FRP 隧道端口",
        ["remote.tab.wan"],
        ["隧道端口"],
      ],
      [
        "remote.wan.publicOrigin",
        "field",
        "remoteControl.publicOrigin",
        "手机 HTTPS 地址",
        ["remote.tab.wan"],
        ["public origin", "域名地址"],
      ],
      [
        "remote.wan.tlsServerName",
        "field",
        "remoteControl.tlsServerName",
        "FRP TLS 服务器名称",
        ["remote.tab.wan"],
        ["tls", "sni"],
      ],
      [
        "remote.wan.autoConnect",
        "field",
        "remoteControl.autoConnectLabel",
        "启动时自动连接",
        ["remote.tab.wan"],
        ["自动连接", "启动"],
      ],
      [
        "remote.wan.token",
        "section",
        "remoteControl.wanTokenTitle",
        "公网令牌",
        ["remote.tab.wan"],
        ["wan token", "令牌"],
      ],
      [
        "remote.wan.tab.deploy",
        "tab",
        "remoteControl.deployNewServer",
        "部署新服务器",
        ["remote.tab.wan"],
        ["deploy", "新服务器"],
      ],
      [
        "remote.wan.tab.import",
        "tab",
        "remoteControl.importBundle",
        "导入已有配置包",
        ["remote.tab.wan"],
        ["import", "配置包"],
      ],
      [
        "remote.wan.tab.manual",
        "tab",
        "remoteControl.manualConfig",
        "手动填写连接信息",
        ["remote.tab.wan"],
        ["manual", "手动配置"],
      ],
      [
        "remote.deploy.step1",
        "section",
        "remoteControl.step1Title",
        "购买前确认：只需要服务器和域名",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["server", "domain", "购买"],
      ],
      [
        "remote.deploy.step2",
        "section",
        "remoteControl.step2Title",
        "先去两个控制台完成这些设置",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["dns", "域名解析", "安全组"],
      ],
      [
        "remote.deploy.step3",
        "section",
        "remoteControl.step3Title",
        "再填写 Snow 连接信息",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["连接信息", "ssh"],
      ],
      [
        "remote.deploy.step4",
        "section",
        "remoteControl.step4Title",
        "检测成功后再自动部署",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["自动部署", "检测"],
      ],
      [
        "remote.deploy.serverIp",
        "field",
        "remoteControl.serverIpLabel",
        "服务器公网 IP",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["ip", "公网 ip"],
      ],
      [
        "remote.deploy.rootDomain",
        "field",
        "remoteControl.rootDomainLabel",
        "你的根域名",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["domain", "根域名"],
      ],
      [
        "remote.deploy.sshUsername",
        "field",
        "remoteControl.sshUsername",
        "SSH 用户名",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["ssh user", "用户名"],
      ],
      [
        "remote.deploy.sshPort",
        "field",
        "remoteControl.sshPort",
        "SSH 端口",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["ssh port"],
      ],
      [
        "remote.deploy.frpBindPort",
        "field",
        "remoteControl.frpBindPort",
        "FRP 控制端口",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["frp bind port"],
      ],
      [
        "remote.deploy.authMethod",
        "field",
        "remoteControl.authMethod",
        "登录方式",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["认证方式"],
      ],
      [
        "remote.deploy.password",
        "field",
        "remoteControl.authPassword",
        "SSH 密码",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["password", "root 密码"],
      ],
      [
        "remote.deploy.keyFile",
        "field",
        "remoteControl.sshKeyFile",
        "SSH 私钥文件",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["private key", "pem"],
      ],
      [
        "remote.deploy.passphrase",
        "field",
        "remoteControl.passphrase",
        "私钥密码（没有可留空）",
        ["remote.tab.wan", "remote.wan.tab.deploy"],
        ["passphrase", "私钥密码"],
      ],
      [
        "remote.manual.title",
        "section",
        "remoteControl.manualFormTitleNew",
        "填写公网连接信息",
        ["remote.tab.wan", "remote.wan.tab.manual"],
        ["公网配置", "连接信息"],
      ],
      [
        "remote.manual.enabled",
        "field",
        "remoteControl.tunnelEnabled",
        "启用公网远控",
        ["remote.tab.wan", "remote.wan.tab.manual"],
        ["公网开关"],
      ],
      [
        "remote.manual.autoConnect",
        "field",
        "remoteControl.tunnelAutoConnect",
        "Snow 启动后自动连接",
        ["remote.tab.wan", "remote.wan.tab.manual"],
        ["自动连接"],
      ],
      [
        "remote.manual.serverPort",
        "field",
        "remoteControl.frpServerPort",
        "FRP 端口",
        ["remote.tab.wan", "remote.wan.tab.manual"],
        ["frp port"],
      ],
      [
        "remote.manual.token",
        "field",
        "remoteControl.frpToken",
        "FRP 凭据",
        ["remote.tab.wan", "remote.wan.tab.manual"],
        ["凭据", "密钥"],
      ],
      [
        "remote.manual.caCert",
        "field",
        "remoteControl.frpCa",
        "FRP CA 证书（PEM）",
        ["remote.tab.wan", "remote.wan.tab.manual"],
        ["证书", "pem"],
      ],
    ],
  },
  {
    view: "usage-settings",
    entries: [
      [
        "usage.profileFilter",
        "field",
        "settings.usageProfileFilterLabel",
        "API profile",
        [],
        ["接口配置筛选", "供应商"],
      ],
      [
        "usage.cacheHitRate",
        "field",
        "settings.usageCacheHitRate",
        "Cache hit rate",
        [],
        ["缓存命中率"],
      ],
      [
        "usage.totalTokens",
        "field",
        "settings.usageTotalTokens",
        "Total tokens",
        [],
        ["token 总量"],
      ],
      [
        "usage.inputTokens",
        "field",
        "settings.usageInputTokens",
        "Input tokens",
        [],
        ["输入 token"],
      ],
      [
        "usage.outputTokens",
        "field",
        "settings.usageOutputTokens",
        "Output tokens",
        [],
        ["输出 token"],
      ],
      [
        "usage.cacheWrite",
        "field",
        "settings.usageCacheCreation",
        "Cache write",
        [],
        ["缓存写入"],
      ],
      [
        "usage.cacheRead",
        "field",
        "settings.usageCacheRead",
        "Cache read",
        [],
        ["缓存读取"],
      ],
      [
        "usage.totalRequests",
        "field",
        "settings.usageTotalRequests",
        "Total requests",
        [],
        ["总请求数"],
      ],
      [
        "usage.successRate",
        "field",
        "settings.usageSuccessRate",
        "Success rate",
        [],
        ["成功率"],
      ],
      [
        "usage.errorRequests",
        "field",
        "settings.usageErrorRequests",
        "Error requests",
        [],
        ["失败请求"],
      ],
      [
        "usage.trendTitle",
        "section",
        "settings.usageTrendTitle",
        "Daily trend",
        [],
        ["每日趋势", "折线图"],
      ],
      [
        "usage.donutTitle",
        "section",
        "settings.usageDonutTitle",
        "Model share",
        [],
        ["模型占比", "环形图"],
      ],
      [
        "usage.modelBreakdownTitle",
        "section",
        "settings.usageModelBreakdownTitle",
        "Model usage",
        [],
        ["模型用量", "按模型统计"],
      ],
      [
        "usage.heatmapTitle",
        "section",
        "settings.usageHeatmapTitle",
        "Daily usage heatmap",
        [],
        ["热力图"],
      ],
      [
        "usage.recordsTitle",
        "section",
        "settings.usageRecordsTitle",
        "Usage records",
        [],
        ["用量记录", "调用明细"],
      ],
      [
        "usage.clearTitle",
        "section",
        "settings.usageClearTitle",
        "Clear usage data",
        [],
        ["清除用量记录"],
      ],
      [
        "usage.clearSince",
        "field",
        "settings.usageSinceDate",
        "Start date",
        [],
        ["开始日期"],
      ],
      [
        "usage.clearUntil",
        "field",
        "settings.usageUntilDate",
        "End date",
        [],
        ["结束日期"],
      ],
    ],
  },
  {
    view: "system-logs",
    entries: [
      [
        "logs.levelAll",
        "tab",
        "settings.systemLogsLevelAll",
        "All",
        [],
        ["全部级别", "日志级别"],
      ],
      ["logs.levelDebug", "tab", null, "DEBUG", [], ["调试日志", "日志级别"]],
      ["logs.levelInfo", "tab", null, "INFO", [], ["信息日志", "日志级别"]],
      ["logs.levelWarn", "tab", null, "WARN", [], ["警告日志", "日志级别"]],
      ["logs.levelError", "tab", null, "ERROR", [], ["错误日志", "日志级别"]],
      [
        "logs.requestLogging",
        "field",
        "settings.systemLogsRequestLogging",
        "Request logging",
        [],
        ["请求日志", "记录原始请求"],
      ],
      [
        "logs.requestLoggingDuration",
        "field",
        "settings.systemLogsRequestLoggingDuration",
        "Auto-disable after",
        [],
        ["自动关闭", "记录时长"],
      ],
    ],
  },
];

const SETTINGS_PAGE_ITEMS: ReadonlyMap<MainContentView, SettingsItem> = new Map(
  SETTINGS_ITEMS.map((item) => [item.view, item]),
);

const buildEntries = (): SettingsSearchEntry[] => {
  const entries: SettingsSearchEntry[] = [];

  for (const group of RAW_GROUPS) {
    const page = SETTINGS_PAGE_ITEMS.get(group.view);
    const rawById = new Map(group.entries.map((entry) => [entry[0], entry]));

    if (page) {
      entries.push({
        id: `page:${group.view}`,
        view: group.view,
        kind: "page",
        labelKey: page.labelKey,
        label: page.defaultLabel,
        trail: [],
        keywords: [],
      });
    }

    for (const [id, kind, labelKey, label, trail, keywords] of group.entries) {
      entries.push({
        id,
        view: group.view,
        kind,
        labelKey,
        label,
        trail: trail
          .map((trailId) => rawById.get(trailId))
          .filter((item): item is RawEntry => Boolean(item))
          .map((item) => ({ labelKey: item[2], label: item[3] })),
        keywords,
      });
    }
  }

  return entries;
};

export const SETTINGS_SEARCH_ENTRIES: SettingsSearchEntry[] =
  buildEntries().filter((entry) => !HIDDEN_ENTRY_IDS.has(entry.id));

export const SETTINGS_SEARCH_RESULT_LIMIT = 40;

export const searchSettingsEntries = (
  query: string,
  resolveLabel: (entry: SettingsSearchEntry) => string,
): SettingsSearchEntry[] => {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return [];
  }

  const scored: { entry: SettingsSearchEntry; score: number }[] = [];

  for (const entry of SETTINGS_SEARCH_ENTRIES) {
    const localized = resolveLabel(entry).toLowerCase();
    const haystack = `${localized} ${entry.label.toLowerCase()} ${entry.keywords.join(" ")}`;
    const index = haystack.indexOf(normalized);

    if (index < 0) {
      continue;
    }

    scored.push({
      entry,
      score: localized.startsWith(normalized) ? index : index + 100,
    });
  }

  scored.sort((a, b) => a.score - b.score);

  return scored
    .slice(0, SETTINGS_SEARCH_RESULT_LIMIT)
    .map((item) => item.entry);
};

export const getSettingsPageItem = (
  view: MainContentView,
): SettingsItem | undefined => SETTINGS_PAGE_ITEMS.get(view);
